---
title: 'Replication of Colombatto et al. (2023): Vaccine Nationalism Counterintuitively
  Erodes Public Trust in Leaders'
author: "Zhipei Wang & Jonathan Koop"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Study 4
## load data
```{r}
data4 <- read.csv("S4 - Data.csv") # n = 304
```

## exclusions
```{r}
head(data4)
```

```{r}
data4 <- filter(data4, heard_stud == "No") # n = 270
```


## characteristics
```{r}
table(data4$gender)
```

```{r}
mean(data4$age, na.rm = T) # 1 NA in age
```

```{r}
table(data4$education)
table(data4$education)/nrow(data4)
```

```{r}
summary(data4$politics)
sd(data4$politics)
```

```{r}
table(data4$job_sector)
table(data4$job_sector)/nrow(data4)
```

```{r}
head(sort(table(data4$job), decreasing = T), 5)
```

```{r}
summary(data4$job_contact_polit_1)
sd(data4$job_contact_polit_1)
```

```{r}
summary(data4$job_contact_citiz_1)
sd(data4$job_contact_citiz_1)
```

## analyses
```{r}
data4 %>% 
  mutate(predicted = case_when(predicted == "Leader 1 and Leader 2 were trusted equally" ~ "Neither",
                       predicted == "Leader 1" ~ leader1,
                       (predicted == "Leader 2" & leader1 == "Nationalism") ~ "Redistribution",
                       (predicted == "Leader 2" & leader1 == "Redistribution") ~ "Nationalism"),
         predicted = factor(predicted, levels = c("Redistribution", "Neither", "Nationalism"))) -> data4
```


```{r}
summ4 <- count(data4, predicted)
summ4
```


```{r}
# overall
chisq.test(x=summ4$n, correct = FALSE, p=rep(1/3, 3))
```

```{r}
# w
sqrt(31.2/sum(summ4$n))
```

```{r}
# Redistribution vs. Nationalism
chisq.test(x=c(filter(summ4, predicted == "Redistribution")$n,
                     filter(summ4, predicted == "Nationalism")$n), correct = FALSE, p=rep(1/2, 2))
```

```{r}
# w
sqrt(1.4595/(120+102))
```

```{r}
# policy support
summary(data4$support)
sd((data4$support))
```
```{r}
plot(density(data4$support)) # t test assumption not met, so chose non-parametric test wilcoxon
```

```{r}
wilcox.test(data4$support, mu = 4)
```

```{r}
wilcox_effsize(data4, support ~1, mu = 4, ci=TRUE) # didn't talk about the choice of mu = 4 in paper, but the magnitude is large (tried for mu = 5, magnitude = small)
```

## across Study 3 vs 4
```{r}
# load data
data3 <- cbind(read.csv("S3 - Data.csv"), study_n = 3)
data34 <- rbind(data3, cbind(read.csv("S4 - Data.csv"), study_n = 4))
```


```{r}
head(data34)
```

```{r}
# exclusions
data34 <- filter(data34, heard_stud=="No")
```


```{r}
data34 %>% 
  mutate(predicted = case_when(predicted == "Leader 1 and Leader 2 were trusted equally" ~ "Neither",
                       predicted == "Leader 1" ~ leader1,
                       (predicted == "Leader 2" & leader1 == "Nationalism") ~ "Redistribution",
                       (predicted == "Leader 2" & leader1 == "Redistribution") ~ "Nationalism"),
         predicted = factor(predicted, levels = c("Redistribution", "Neither", "Nationalism"))) -> data34
```


```{r}
summ34 <- count(data34, study_n, predicted)
summ34 <- spread(summ34, predicted, n)
rownames(summ34) <- summ34$study_n
summ34$study_n <- NULL
```


```{r}
# overall
chisq.test(x = summ34)
```
```{r}
# w
sqrt(16.691/nrow(data34))
```




```{r}
# Redistribution vs. Nationalism
summ34$Neither <- NULL
chisq.test(x=summ34)
```

```{r}
# w
sqrt(15.812/(52+106+120+102))
```


## policy preferences across Studies 1 through 4
```{r}
# load data

#study 1
data_tmp <- read.csv("S1 - Data.csv", fileEncoding="UTF-8-BOM")

data_tmp %>%
    filter(duplicate_IP == 0, duplicate_ID == 0,
           survey_c == country,
           att_check1 == "TikTok",
           att_check2 == "Roses can suffer with pests like aphids and blackfly",
           comp_check == "How much I trusted the mayor") %>%
  select(sub_n, support) %>%
  mutate(study_n = 1) -> data

# study 2
data_tmp <- read.csv("S2 - Data.csv")

data_tmp %>%
    filter(consent == "Yes", att_check1 == "TikTok",
           att_check2 == "Roses can suffer with pests like aphids and blackfly",
           comp_check == "How much I trusted the mayor") %>%
  select(sub_n, support) %>%
  mutate(study_n = 2) %>%
  rbind(data) -> data

# study 3
data_tmp <- read.csv("S3 - Data.csv")

data_tmp %>%
  filter(heard_stud=="No") %>%
  select(sub_n, support) %>%
  mutate(study_n = 3) %>%
  rbind(data) -> data

# study 4
data_tmp <- read.csv("S4 - Data.csv")

data_tmp %>%
  filter(heard_stud=="No") %>%
  select(sub_n, support) %>%
  mutate(study_n = 4) %>%
  rbind(data) -> data
```


```{r}
head(data)
```


```{r}
boxplot(support ~ study_n, data = data) # not normal, similar distributions?
```

```{r}
kruskal.test(support ~ study_n, data = data)
```

```{r}
pairwise.wilcox.test(data$support, data$study_n, p.adjust.method = "bonf")
```

# Study 5

## load data
```{r}
data5 <- read.csv("S5 - Data.csv")
```

```{r}
# composite DV
data5$trust_avg <- (data5$trust_1+data5$trust_2)/2
```


```{r}
colSums(is.na(data5)) # no missing more than half
```

## exclusions
```{r}
data5 %>%
  mutate(failed_att1 = att_check1 != "TikTok",
         failed_att2 = att_check2 != "Roses can suffer with pests like aphids and blackfly",
         failed_comp = comp_check != "How much I trusted the mayor") -> data5

data5 <- filter(data5, duplicate_IP == 0, duplicate_ID == 0)
data5 <- filter(data5, failed_att1 == 0, failed_att2 == 0)
data5 <- filter(data5, country == "United States")
data5 <- filter(data5, failed_comp == 0)
```


```{r}
table(data5$gender)
```

```{r}
mean(data5$age, na.rm = T) # 1 NA
```

## variable recoding
```{r}
data5 %>%
  
  mutate(vnat_b = gsub(".*ensure that there are enough vaccines for people.*", "Keep",
                       gsub(".*ensure that people in developing countries have access to vaccines.*",
                            "Distribute", vnat_b)),
         
         gender_rec = if_else(gender %in% c("Woman", "Man"), gender, "Other"),
         gender_rec = factor(gender_rec, levels = c("Woman", "Man", "Other")),
         
         race_rec = gsub("Australian", "White", race),
         race_rec = if_else(race_rec == "White", "White", "Other"),
         race_rec = factor(race_rec, levels = c("White", "Other")),
         
         cond = factor(cond, c("Redistribution", "Nationalism"))) -> data5
```

## analyses
```{r}
# effective coding
data5$cond_rec <- recode(data5$cond, "Nationalism" = -0.5, "Redistribution" = 0.5)
```



```{r}
# Set contrasts
options(contrasts = c("contr.treatment", "contr.poly"))
```


```{r}
lm5 <- lm(trust_avg ~ gender_rec + age + race_rec 
          + education + ses2 + politics + religious 
          + support + cond_rec, data = data5)
summary(lm5)$coefficients
```

```{r}
summary(lm5)$coefficients
```


```{r}
confint(lm5, "cond_rec", level = 0.95)
```


```{r}
plot(lm5)
```

## Exploratory Analyses
```{r}
plot(density(filter(data5, vnat_b == "Keep", 
                      cond == "Redistribution")$trust_avg))
```

```{r}
plot(density(filter(data5, vnat_b == "Keep", 
                      cond == "Nationalism")$trust_avg))
```


```{r}
# participants who chose nationalism 
t.test(filter(data5, vnat_b == "Keep", 
                      cond == "Redistribution")$trust_avg,
               filter(data5, vnat_b == "Keep", 
                      cond == "Nationalism")$trust_avg)
```

```{r}
# cohens_d(filter(data5, vnat_b == "Keep", 
#                       cond == "Redistribution")$trust_avg,
#          filter(data5, vnat_b == "Keep", 
#                       cond == "Nationalism")$trust_avg)
```

```{r}
plot(density(filter(data5, politics== 7, 
                      cond == "Redistribution")$trust_avg))
```

```{r}
plot(density(filter(data5, politics== 7, 
                      cond == "Nationalism")$trust_avg))
```


```{r}
# Conservative participants
t.test(filter(data5, politics== 7, 
                      cond == "Redistribution")$trust_avg,
       filter(data5, politics == 7, 
                      cond == "Nationalism")$trust_avg)

# cohens_d(filter(data5, politics == 7, 
#                       cond == "Redistribution")$trust_avg,
#          filter(data5, politics == 7, 
#                       cond == "Nationalism")$trust_avg)
```

```{r}
wilcox.test(filter(data5, politics== 7, 
                      cond == "Redistribution")$trust_avg,
       filter(data5, politics == 7, 
                      cond == "Nationalism")$trust_avg)
```

# study 6
## load data
```{r}
data6 <- read.csv("S6 - Data.csv")
```

```{r}
# composite DV
data6$trust_avg <- (data6$trust_1+data6$trust_2)/2
```


```{r}
colSums(is.na(data6)) # no missing
```

## variable recoding
```{r}
data6 %>%
  
  mutate(vnat_b = gsub(".*ensure that there are enough vaccines for people.*", "Keep",
                       gsub(".*ensure that people in developing countries have access to vaccines.*",
                            "Distribute", vnat_b)),
         
         gender_rec = if_else(gender %in% c("Woman", "Man"), gender, "Other"),
         gender_rec = factor(gender_rec, levels = c("Woman", "Man", "Other")),
         
         race_rec = gsub("Australian", "White", race),
         race_rec = if_else(race_rec == "White", "White", "Other"),
         race_rec = factor(race_rec, levels = c("White", "Other")),
         
         cond = factor(cond, c("Redistribution", "Nationalism"))) -> data6
```

## exclusions
```{r}
data6 %>%
  mutate(failed_att1 = att_check1 != "TikTok",
         failed_att2 = att_check2 != "Roses can suffer with pests like aphids and blackfly",
         failed_comp = comp_check != "How much I trusted the mayor") -> data6

data6 <- filter(data6, duplicate_IP == 0, duplicate_ID == 0)
data6 <- filter(data6, failed_att1 == 0, failed_att2 == 0)
data6 <- filter(data6, country == "United States")
data6 <- filter(data6, failed_comp == 0)
```


## analyses
```{r}
# effective coding
data6$cond_rec <- recode(data6$cond, "Nationalism" = -0.5, "Redistribution" = 0.5)
```

```{r}
# center variables
data6$politics_raw <- data6$politics
data6$support_raw <- data6$support
data6 <- mutate_at(data6, c("age", "ses2", "politics",
           "religious", "support"), ~scale(.x, center = TRUE, scale=FALSE))
```



```{r}
# Set contrasts
options(contrasts = c("contr.treatment", "contr.poly"))
```


```{r}
lm6 <- lm(trust_avg ~ gender_rec + age + race_rec 
          + education + ses2 + politics + religious 
          + support + cond_rec, data = data6)
lm6
```

```{r}
summary(lm6)$coefficients
```


```{r}
confint(lm6, "cond_rec", level = 0.95)
```

```{r}
plot(lm6)
```


## Exploratory Analyses
```{r}
plot(density(filter(data6, vnat_b == "Keep", 
                      cond == "Redistribution")$trust_avg))
```

```{r}
plot(density(filter(data6, vnat_b == "Keep", 
                      cond == "Nationalism")$trust_avg))
```

```{r}
# participants who chose nationalism 
t.test(filter(data6, vnat_b == "Keep", 
                      cond == "Redistribution")$trust_avg,
               filter(data6, vnat_b == "Keep", 
                      cond == "Nationalism")$trust_avg)
```

```{r}
plot(density(filter(data6, politics_raw== 7, 
                      cond == "Redistribution")$trust_avg))
```

```{r}
plot(density(filter(data6, politics_raw== 7, 
                      cond == "Nationalism")$trust_avg))
```

```{r}
# Conservative participants
t.test(filter(data6, politics_raw== 7, 
                      cond == "Redistribution")$trust_avg,
       filter(data6, politics_raw == 7, 
                      cond == "Nationalism")$trust_avg)
```





# study 7

## load data
```{r}
data7 <- read.csv("S7 - Data.csv")
```


```{r}
data7
```

```{r}
data7 %>%
  
  mutate(vnat_b = gsub(".*ensure that there are enough vaccines for people.*", "Keep",
                       gsub(".*ensure that people in developing countries have access to vaccines.*",
                            "Distribute", vnat_b)),
         
         gender_rec = if_else(gender %in% c("Woman", "Man"), gender, "Other"),
         gender_rec = factor(gender_rec, levels = c("Woman", "Man", "Other")),
         
         race_rec = gsub("Australian", "White", race),
         race_rec = if_else(race_rec == "White", "White", "Other"),
         race_rec = factor(race_rec, levels = c("White", "Other")),
         
         vote = factor(vote, c("Redistribution", "Nationalism"))) -> data7
```


## exclusions
```{r}
colSums(is.na(data7))
```


```{r}
data7 %>%
  mutate(failed_att1 = att_check1 != "TikTok",
         failed_att2 = att_check2 != "Roses can suffer with pests like aphids and blackfly",
         failed_comp = comp_check != "The leader can transfer the full donation to UNICEF or take some of the money for themselves.") -> data7

data7 <- filter(data7, duplicate_IP == 0, duplicate_ID == 0)
data7 <- filter(data7, failed_att1 == 0, failed_att2 == 0)
data7 <- filter(data7, country == "United States")
data7 <- filter(data7, failed_comp == 0)
```

## analyses
```{r}
summ7 <- count(data7, vote)
```


```{r}
binom.test(x = 199, n = 199+37, p = 0.5, alternative = "two.sided", conf.level = 0.95)
```

## participant analyses

```{r}
# participants who chose Nationalism
count(filter(data7, vnat_b == "Keep"), vote, vnat_b)
```


```{r}
binom.test(x = 101, n = 101+35, p = 0.5, alternative = "two.sided", conf.level = 0.95)
```


```{r}
# Conservative participants
count(filter(data7, politics == 7), vote)
```


```{r}
binom.test(x = 9, n = 15, p = 0.5, alternative = "two.sided", conf.level = 0.95)
```






